---

    -   name: Download Statping
        get_url:
            url: https://statping.com/install.sh
            dest: /tmp/install.sh
        
    -   name: Execute Statping
        shell: bash /tmp/install.sh

    -   name: Set the Statping Service
        become: true
        template:
            src: "statping.service.j2"
            dest: "/etc/systemd/system/statping.service"

    -   name: Enable and start Statping service
        systemd:
            state: started
            daemon_reload: yes
            enabled: yes
            name: statping